baseURL = "/"
languageCode = "en-us"
title = "Home"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 10

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@corneliudev"
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addFrame = false
  addDot = false
